version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=112529
      - MYSQL_DATABASE=proyectdb
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql # Monta el volumen para persistencia de datos

  app:   
    build: .
    depends_on:
      - mysqldb
    links:  
      - mysqldb
    ports:
      - 8087:8087

volumes:
  mysql-data: 
